### PR TITLE
feat: enable linking multiple modules via the manifest

### PR DESCRIPTION
**Pull request by chrisdickinson**
Enable linking multiple modules via the manifest; walk from the `main`
module to all dependencies. Notable changes:

- Modules are preferred over host imports. (If the main module requests "foo",
  and there's another manifest module named "foo", the main module will get the
  exports of that module, even if the host also provides "foo".)
- Only modules reachable via the main module are instantiated. Other modules are
  ignored. (Previously, all modules would be instantiated.)
- Modules can share memories, tables, globals, and functions. Circular imports are
  resolved for functions -- a trampoline is inserted by the runtime -- but all other
  circular import types fail.

I have some open questions:

- What should our module initialization behavior be for sub-modules with hs_init/initialize/_start functions?
- Should we initialize command modules once per import request? (Wasmtime appears to do this, but I need to verify.)
- Should we call `wasi.initialize` once per manifest or many times within the dep tree?

Fixes https://github.com/extism/js-sdk/issues/29.

### CODE REVIEW

**Comment by zshipko** [comment]
Super excited about this!

 > What should our module initialization behavior be for sub-modules with hs_init/initialize/_start functions?

This is tricky - I was just exploring this the other day and noticed that Haskell sub-modules sometimes don't get initialized correctly. In wasmtime this would require each sub-module to be instantiated, so we're only calling those initializers for the main module there. I'm still investigating that path a little bit, but as of now only the main module gets initialized in Rust - I think this is how the Go SDK works too, although the implementation is closer to this one so we would probably have more flexibility there (cc @mhmd-azeez).

Once we exercise some of the linking abilities more we may find that we do really need to initialize all the sub-modules, it could make sense to go through and update all the runtimes to match at that point. Definitely worth some further discussion!

 > Should we initialize command modules once per import request? (Wasmtime appears to do this, but I need to verify.)

Is this about importing the `_start` function from a linked command module? My understanding is that once `_start` returns any initialization should be considered invalid.

 > Should we call wasi.initialize once per manifest or many times within the dep tree?

This is only done once for the main module in the other runtimes, but I'm not sure how `wasi.initialize` differs from `wasmtime_wasi::add_to_linker` so it may be necessary to call it multiple times here.

**Review by zshipko — COMMENTED** [review]
I just took a look through the implementation and it looks really nice! A lot less code than I was expecting :smile: 

I know there are still some TODOs, but I don't see any other immediate issues on this pass. I will do a final review once you get the chance to make those initialization changes.

**Comment by mhmd-azeez** [comment]
> This is tricky - I was just exploring this the other day and noticed that Haskell sub-modules sometimes don't get initialized correctly. In wasmtime this would require each sub-module to be instantiated, so we're only calling those initializers for the main module there. I'm still investigating that path a little bit, but as of now only the main module gets initialized in Rust - I think this is how the Go SDK works too, although the implementation is closer to this one so we would probably have more flexibility there (cc mhmd-azeez).

Yes, we only initialize the main module in the Go SDK too. Once this is merged, can apply the same logic there too

**Comment by chrisdickinson** [comment]
OK, latest update: I have to initialize a WASI instance for every module in the tree that requests it. (This is the only way I could get the WASI interface to work for side modules that use WASI.) The good news is that enabling WASI is free for modules that don't _use_ WASI now. The bad news is that you might end up with multiple WASI instances for complicated manifests – and I'm not sure the degree to which they'll "agree" on the state of the world (does a fd from one WASI instance map to a fd from the other WASI instance?) but it's the closest I could get the behavior to match wasmtime, I think. The neutral news is that I don't think many users will run into this in practice (Fingers crossed 😅🤞🏻)

**Review by zshipko — APPROVED** [review]
Looks great - we can track any future WASI/linking issues, but having something in JS that works for most cases is a huge deal!

**Pull request merged**
